USE [LVWWG];

DROP TABLE [DONATIONDETAILS];
DROP TABLE [IMAGEDETAILS];
DROP TABLE [LINKDETAILS];
DROP TABLE [MARKETITEMS];
DROP TABLE [MEETINGS];

CREATE TABLE [DBO].[DONATIONDETAILS] (
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[ORGANIZATIONNAME] [VARCHAR](100) NOT NULL,
	[DONATIONYEAR] [VARCHAR](4) NOT NULL,
	[BLOCKSETS] [NUMERIC](6, 0) NULL,
	[RACECARS] [NUMERIC](6, 0) NULL,
	[ROCKINGHORSES] [NUMERIC](6, 0) NULL,
	[TRAINS] [NUMERIC](6, 0) NULL,
	[WANDS] [NUMERIC](6, 0) NULL,
	[MISC] [VARCHAR](100) NULL,
) ON [PRIMARY];

CREATE TABLE [DBO].[IMAGEDETAILS] (
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[IMAGESOURCE] [VARCHAR](256) NOT NULL,
	[ALT] [VARCHAR](100) NOT NULL,
	[TITLE] [VARCHAR](100) NOT NULL,
	[SUBTITLE] [VARCHAR](100) NULL,
) ON [PRIMARY];

CREATE TABLE [DBO].[LINKDETAILS] (
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[COMPANYNAME] [VARCHAR](100) NOT NULL,
	[STREETADDRESS] [VARCHAR](100) NULL,
	[STREETADDRESS2] [VARCHAR](100) NULL,
	[CITYSTATEADDRESS] [VARCHAR](100) NULL,
	[CONTACT] [VARCHAR](100) NULL,
	[PHONE] [VARCHAR](20) NULL,
	[MESSAGE] [VARCHAR](256) NULL,
	[URL] [VARCHAR](100) NULL,
	[CATEGORY] [VARCHAR](100) NOT NULL,
) ON [PRIMARY];

CREATE TABLE [DBO].[MARKETITEMS] (
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[POSTEDDATE] [DATETIME] NOT NULL,
	[POSTEDBY] [VARCHAR](100) NOT NULL,
	[CONTACTINFO] [VARCHAR](100) NOT NULL,
	[NAME] [VARCHAR](100) NOT NULL,
	[DESCRIPTION] [VARCHAR](100) NOT NULL,
	[PRICE] [NUMERIC](18, 0) NOT NULL,
	[IMAGE] [VARCHAR](256) NULL,
) ON [PRIMARY];

CREATE TABLE [DBO].[MEETINGS](
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[DATETIME] [DATETIME] NOT NULL,
	[LOCATION] [VARCHAR](100) NOT NULL,
	[PRESENTER] [VARCHAR](100) NULL,
	[TOPIC] [VARCHAR](256) NULL
) ON [PRIMARY];

CREATE TABLE [DBO].[MEMBERS] (
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
  [FIRSTNAME] [VARCHAR](50) NOT NULL,
  [LASTNAME] [VARCHAR](50) NOT NULL,
  [EMAIL] [VARCHAR](100) NOT NULL,
  [PASSWORD] [VARCHAR](100) NOT NULL,
  [ADMIN] [VARCHAR](1) NOT NULL
) ON [PRIMARY];

-- INSERT INTO [dbo].[MEETINGS] ([ID],[DATETIME],[LOCATION],[PRESENTER],[TOPIC])
--   VALUES (NEWID(),'2022-03-15T22:30:00Z', 'Woodcraft Store, Parkway Shopping Center','wEBMASTER Swope','New website sneak peak');
